### ISSUE TITLE
Geshi downloadable snippet

### ISSUE THREAD

**Issue by MrReSc** [turnermm/ckgedit#453]
If I want to insert a snippet with Geshi, which should be downloadable, nothing happens when I press OK.
All I see in the log is:

```
172.21.0.1 - - [11/Jan/2019:16:12:10 +0000] "GET /lib/exe/ajax.php?call=geshi_sel HTTP/1.1" 200 1013
172.21.0.1 - - [11/Jan/2019:16:12:10 +0000] "POST /lib/exe/ajax.php HTTP/1.1" 200 11
```

![download_geshi](https://user-images.githubusercontent.com/24952268/51045130-24b29480-15c3-11e9-984b-094e185d8184.png)

The snippet insert as normal codeblock works. I use the Docker container **Release 2018-04-22b "Greebo"** and ckgedit installed from the Plugin Manager. 

Am I doing something wrong or is there another plugin missing? I tested it with Firefox, Chrome and Chromium.

**Comment by turnermm** [comment]
See: https://www.mturner.org/devel/playground/geshi

**Comment by turnermm** [comment]
I was going to look into this issue, but now I'm unable to reproduce the problem.  It may then have to do with context, and unless I can repeat the context I can't see what's going on.

**Comment by MrReSc** [comment]
Thank you for your effort. 
What do you mean by context? What information do you need? 
As I mentioned before, I used the docker container [bitnami/dokuwiki](https://hub.docker.com/r/bitnami/dokuwiki/) and ckgedit from the Plugin Manager.

![2019-01-16_13-21-50](https://user-images.githubusercontent.com/24952268/51248872-c7875c00-1991-11e9-9d42-95e6286981df.gif)

**Comment by turnermm** [comment]
The following video shows that it does work:
https://www.youtube.com/watch?v=l6Z-ZnHni5w

But why and when it does not work is difficult to determined because the problem is not repeatable on demand.
So, the first thing would be: What browser are you using and on what operating system?

**Comment by MrReSc** [comment]
We use Firefox and Edge on Windows 10 and Firefox on Fedora 29. I also tested it with chromium.

In the meantime I created a new DokuWiki Contaier and installed only ckgedit and no other plugin. Unfortunately I have exactly the same problem.

To avoid problems with my servers I spinn up a new container with [play-with-docker](https://labs.play-with-docker.com), unfortunately with the same result. 

With the following docker-compose.yml you can reproduce my configuration exactly. With this configuration the problem is reproducible.

```
version: '2'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'dokuwiki_data:/bitnami'
    environment:
      - DOKUWIKI_PASSWORD=my_password
volumes:
  dokuwiki_data:
    driver: local
```
